filebeat.inputs:
  - type: log
    paths:
      - /var/logs/nginx/*.log
    tags:
      - nginx
  - type: log
    paths:
      - /var/logs/nginx2/*.log
    tags:
      - nginx2
  - type: log
    paths:
      - /var/logs/nginx3/*.log
    tags:
      - nginx3
output.elasticsearch:
  hosts:
    - "${ELASTICSEARCH_PROTOCOL}://es1:${ELASTICSEARCH_PORT}"
  ssl:
    certificate_authorities: ["${FILEBEAT_CERTS_DIRECTORY}/${FILEBEAT_SSL_CERT_FILE}"]
    verification_mode: certificate
  username: ${FILEBEAT_USER}
  password: ${FILEBEAT_PASSWORD}