filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/nginx/*.log
    # tags:
    #   - nginx-access
output.logstash:
  enabled: true
  hosts:
    - "logstash:${LOGSTASH_PORT}"
  ssl:
    certificate_authorities: ["${FILEBEAT_CERTS_DIRECTORY}/${LOGSTASH_HTTP_SSL_CERT}"]
    verification_mode: certificate