filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/nginx/*.log
    tags:
      - nginx-access
output.logstash:
  enabled: true
  hosts:
    -logstash:5044
  username: elastic
  password: elastic
# Загружает панели мониторинг Filebeat
# setup.kibana:
#   host: http://kibana:${KIBANA_PORT}
#   username: elastic
#   password: ${ELASTICSEARCH_PASSWORD}