filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/nginx/*.log
    tags:
      - nginx-access
output.logstash:
  enabled: true
  hosts:
    - logstash:5044
# Загружает панели мониторинг Filebeat
# setup.kibana:
#   host: http://kibana:5601
#   username: elastic
#   password: elastic