filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/nginx/*.log
    # tags:
    #   - nginx-access
output.elasticsearch:
  hosts:
    - "${ELASTICSEARCH_PROTOCOL}://es1:${ELASTICSEARCH_PORT}"
  ssl:
    certificate_authorities: ["${FILEBEAT_CERTS_DIRECTORY}/${FILEBEAT_SSL_CERT_FILE}"]
    verification_mode: certificate
  username: ${FILEBEAT_USER}
  password: ${FILEBEAT_PASSWORD}