version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:80
    restart: always
    networks:
      - testNetwork
networks:
  testNetwork:
    driver: bridge
