services:
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    volumes:
      - ./alertmanager_configs:/etc/alertmanager
    restart: always
    networks:
      - ${NETWORK_NAME}
  alertmanager-bot:
    image: metalmatze/alertmanager-bot:latest
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_ADMIN: ${TELEGRAM_ADMIN_ID}
      STORE: bolt
      # LISTEN_ADDR: 0.0.0.0:8080
    volumes:
    - ${ALERTMANAGER_BOT_HOST_DATA_DIRECTORY}:/data
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
