services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA_DIRECTORY}:/prometheus
    restart: always
