services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - ${GF_PORT}:${GF_PORT}
    volumes:
      - ${GF_HOST_DATA_DIRECTORY}:/var/lib/grafana
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
