services:
  node_exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.procfs=${NODE_EXPORTER_HOST_PROC_DIRECTORY}"
      - "--path.sysfs=${NODE_EXPORTER_HOST_SYS_DIRECTORY}"
      - "--path.rootfs=${NODE_EXPORTER_HOST_FS_DIRECTORY}"
    volumes:
      - /proc:${NODE_EXPORTER_HOST_PROC_DIRECTORY}:ro
      - /sys:${NODE_EXPORTER_HOST_SYS_DIRECTORY}:ro
      - /:${NODE_EXPORTER_HOST_FS_DIRECTORY}:ro
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
