services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=${PROMETHEUS_CONFIG_PATH}"
      - "--storage.tsdb.retention.time=15d"
      - "--storage.tsdb.retention.size=10GB"
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus.yml:${PROMETHEUS_CONFIG_PATH}
      - ${PROMETHEUS_HOST_DATA_DIRECTORY}:/prometheus
    restart: always
