services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=${PROMETHEUS_CONFIG_PATH}"
      # Очищение старых данных
      - "--storage.tsdb.retention.time=15d"
      # Очищение старых данных
      - "--storage.tsdb.retention.size=30GB"
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus.yml:${PROMETHEUS_CONFIG_PATH}
      - ${PROMETHEUS_HOST_DATA_DIRECTORY}:/prometheus
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
