services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      # Очищение старых данных
      - "--storage.tsdb.retention.time=15d"
      # Очищение старых данных
      - "--storage.tsdb.retention.size=30GB"
      # Позволяет через API забирать dump
      # - "--web.enable-admin-api"
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prom_configs:/etc/prometheus
      - ${PROMETHEUS_HOST_DATA_DIRECTORY}:/prometheus
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
