services:
  pushgateway:
    image: prom/pushgateway:latest
    command:
      # Сохранение метрик в файл
      - "--persistence.file=/data/metrics.data"
      # Период сохранения метрик в файл
      - "--persistence.interval=5m"
    volumes:
      - ${PUSHGATEWAY_HOST_DATA_DIRECTORY}:/data
    restart: always
    networks:
      - ${NETWORK_NAME}
networks:
  telematic:
    name: ${NETWORK_NAME}
    external: ${IS_NETWORK_EXTERNAL}
