route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - receiver: 'pagerduty-critical'
      group_wait: 10s
      matchers:
        - severity="critical"
    - receiver: 'slack-warning'
      group_wait: 60s
      matchers:
        - severity="warning"
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001'
  - name: 'pagerduty-critical'
    pagerduty_configs:
    - routing_key: 'test'
      service_key: 'md5-hash'
  - name: 'slack-warning'
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/token_of_slack'
      channel: '#warnings'
inhibit_rules:
  - source_matchers:
    - severity="critical""
    target_matchers:
    - severity="warning"
    equal: ['instance']

