services:
  es1:
    image: elasticsearch:8.4.3
    ports:
      - 9200:9200
    environment:
    # Позволит отключить автоматическое обнаружение других нод
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    restart: always
    networks:
      - elk
  kibana:
    image: kibana:8.4.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://es1:9200
    restart: always
    depends_on:
      - es1
    networks:
      - elk
  logstash:
    image: logstash:8.4.3
    ports:
      - 5044:5044
    environment:
      - xpack.monitoring.enabled=false
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/logstash.conf
    restart: always
    depends_on:
      - es1
    networks:
      - elk
networks:
  elk:

