services:
  logstash:
    image: logstash:8.4.3
    environment:
      - xpack.monitoring.enabled=false
      - ELASTICSEARCH_USERNAME=${LOGSTASH_SYSTEM_USER}
      - ELASTICSEARCH_PASSWORD=${LOGSTASH_SYSTEM_PASSWORD}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - ELASTICSEARCH_PROTOCOL=${ELASTICSEARCH_PROTOCOL}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - LOGSTASH_CERTS_DIRECTORY=${LOGSTASH_CERTS_DIRECTORY}
      - ELASTICSEARCH_CLIENTS_SSL_CERT_FILE=${ELASTICSEARCH_CLIENTS_SSL_CERT_FILE}
      - LOGSTASH_USER=${LOGSTASH_USER}
      - LOGSTASH_PASSWORD=${LOGSTASH_PASSWORD}
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./certs-creator/certs:${LOGSTASH_CERTS_DIRECTORY}
    restart: always
    depends_on:
      - es1
      - es2
    networks:
      - ${NETWORK_NAME}